version: '3'

services:
  server:
    image: klakegg/hugo:0.101.0-ext-alpine
    container_name: hugo
    command: server
    entrypoint: hugo
    volumes:
      - "./hugo:/src"
    ports:
      - "1313:1313"
    networks:
        - mylocal
  app:
    build: ./proxy
    container_name: proxy
    volumes:
      - "./hugo/content:/app/static"
    ports:
      - "8080:8080"
    networks:
        - mylocal
  prometheus:
    image: prom/prometheus
    volumes:
      - ./proxy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - mylocal
  grafana:
      image: zxcmentor/mygrafana:latest
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      networks:
        - mylocal
networks:
    mylocal:
        driver: bridge